In [25]:
import numpy as np

In [26]:
arr = [1,3,8,10]
print(arr[2])
arr2= [8,4,7,2]
print(arr*3)
print(arr+ arr2)
print(arr[1:3])

8
[1, 3, 8, 10, 1, 3, 8, 10, 1, 3, 8, 10]
[1, 3, 8, 10, 8, 4, 7, 2]
[3, 8]


In [27]:
a = np.array(arr)
print(a)
print(a*3)
print(a+a)
print(a[1:3])

[ 1  3  8 10]
[ 3  9 24 30]
[ 2  6 16 20]
[3 8]


In [28]:
b =np.array(arr2)
print(a+b)

[ 9  7 15 12]


In [36]:
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
one = np.ones((4,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
random = np.random.rand(3,4)
print(random)

[[0.36607747 0.88873235 0.25730091 0.63307721]
 [0.6280754  0.91278601 0.8423466  0.06540047]
 [0.62212845 0.91285345 0.41684326 0.00324728]]


In [42]:
random_int = np.random.randint(10, size=(3,4))
print(random_int)

[[2 9 8 9]
 [2 1 5 8]
 [1 8 5 9]]
