In [45]:
import numpy as np

In [46]:
arr = [1,3,8,10]
print(arr[2])
arr2= [8,4,7,2]
print(arr*3)
print(arr+ arr2)
print(arr[1:3])

8
[1, 3, 8, 10, 1, 3, 8, 10, 1, 3, 8, 10]
[1, 3, 8, 10, 8, 4, 7, 2]
[3, 8]


In [47]:
a = np.array(arr)
print(a)
print(a*3)
print(a+a)
print(a[1:3])

[ 1  3  8 10]
[ 3  9 24 30]
[ 2  6 16 20]
[3 8]


In [48]:
b =np.array(arr2)
print(a+b)

[ 9  7 15 12]


In [49]:
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
one = np.ones((4,3))
print(one)
print(one*7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [51]:
random = np.random.rand(3,4)
print(random)

[[0.87691076 0.71256761 0.14005466 0.03797888]
 [0.30957668 0.59463549 0.22655852 0.78426507]
 [0.80239721 0.93891106 0.60157641 0.63022487]]


In [52]:
random_int = np.random.randint(10, size=(3,4)) #integer between 0 to 10
print(random_int)

[[2 6 9 2]
 [0 2 0 1]
 [4 2 7 1]]


In [53]:
random_i = np.random.randint(5,11, size=(3,4)) #beteen 5 to 11
print(random_i)

[[ 7  5  5  8]
 [ 6  6  6 10]
 [ 8  8  6 10]]


In [54]:
random = np.random.randn(3,4) #rand(n)give pos&neg values
print(random)

[[-1.10722381  0.93572241  1.00666726 -0.09948012]
 [ 1.40289614  0.37152205  0.39913788 -0.61490486]
 [ 0.72368711 -0.28897408  1.19553986 -0.52803752]]


In [56]:
identity_matrix = np.eye(6) #1*1,2*2,3*3,4*4 diagonally 1 and rest 0
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(6) 
print(identity_matrix*7)

[[7. 0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0.]
 [0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 7.]]


In [58]:
allfives = np.full((3,4),5) #3*4 matrix with all 5
print(allfives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
lin = np.linspace(2,5,6) #start,stop,number of points
print(lin)

[2.  2.6 3.2 3.8 4.4 5. ]


In [65]:
lin = np.linspace(0,1,5) 
size_of_sample =10
print(lin)

print(lin*(size_of_sample+1)) #Q1 



[0.   0.25 0.5  0.75 1.  ]
[ 0.    2.75  5.5   8.25 11.  ]
