In [66]:
import numpy as np

In [67]:
arr = [1,3,8,10]
print(arr[2])
arr2= [8,4,7,2]
print(arr*3)
print(arr+ arr2)
print(arr[1:3])

8
[1, 3, 8, 10, 1, 3, 8, 10, 1, 3, 8, 10]
[1, 3, 8, 10, 8, 4, 7, 2]
[3, 8]


In [68]:
a = np.array(arr)
print(a)
print(a*3)
print(a+a)
print(a[1:3])

[ 1  3  8 10]
[ 3  9 24 30]
[ 2  6 16 20]
[3 8]


In [69]:
b =np.array(arr2)
print(a+b)

[ 9  7 15 12]


In [70]:
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [71]:
one = np.ones((4,3))
print(one)
print(one*7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [72]:
random = np.random.rand(3,4)
print(random)

[[0.41431829 0.95575434 0.72108686 0.81119963]
 [0.75349836 0.23928405 0.20418104 0.64426195]
 [0.90112247 0.49860469 0.49243838 0.45816143]]


In [73]:
random_int = np.random.randint(10, size=(3,4)) #integer between 0 to 10
print(random_int)

[[0 0 0 7]
 [5 0 0 1]
 [3 0 5 0]]


In [74]:
random_i = np.random.randint(5,11, size=(3,4)) #beteen 5 to 11
print(random_i)

[[ 7  9 10  6]
 [ 7  5  5 10]
 [10  6  5  5]]


In [75]:
random = np.random.randn(3,4) #rand(n)give pos&neg values
print(random)

[[ 0.00624869 -0.48559023  0.29386437 -0.02116977]
 [ 1.44556053 -0.27739211  0.31101803 -0.03591218]
 [-0.76910479  1.4493831  -1.12572905  0.45707571]]


In [76]:
identity_matrix = np.eye(6) #1*1,2*2,3*3,4*4 diagonally 1 and rest 0
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [77]:
identity_matrix = np.eye(6) 
print(identity_matrix*7)

[[7. 0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0.]
 [0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 7.]]


In [78]:
allfives = np.full((3,4),5) #3*4 matrix with all 5
print(allfives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [79]:
lin = np.linspace(2,5,6) #start,stop,number of points
print(lin)

[2.  2.6 3.2 3.8 4.4 5. ]


In [80]:
lin = np.linspace(0,1,5) 
size_of_sample =10
print(lin)

print(lin*(size_of_sample+1)) #Q1 



[0.   0.25 0.5  0.75 1.  ]
[ 0.    2.75  5.5   8.25 11.  ]
